apiVersion: v1
kind: Namespace
metadata:
  name: jjaramillo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: jjaramillo
data:
  USER_KEY: "tu_clave_de_usuario"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: jjaramillo
type: Opaque
data:
  # El password debe estar en base64 (ej: 'password' es cGFzc3dvcmQ=)
  BD_PASSWORD: cGFzc3dvcmQ= 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: jjaramillo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: curso-devops
  template:
    metadata:
      labels:
        app: curso-devops
    spec:
      containers:
      - name: app-container
        image: ghcr.io/jnjaramillom-sketch/curso-devops-lab3:latest
        ports:
        - containerPort: 3000
        env:
        - name: USER_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: USER_KEY
        - name: BD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: BD_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: jjaramillo
spec:
  selector:
    app: curso-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP