apiVersion: v1
kind: Namespace
metadata:
  name: jjaramillo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: jjaramillo
data:
  USER_KEY: "jnjaramillo"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: jjaramillo
type: Opaque
data:
  BD_PASSWORD: bXlwYXNzd29yZA==  # "mypassword" en base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: jjaramillo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: curso-devops
  template:
    metadata:
      labels:
        app: curso-devops
    spec:
      containers:
      - name: app
        image: ghcr.io/jnjaramillom-sketch/curso-devops-lab3:latest
        ports:
        - containerPort: 3000
        env:
        - name: USER_KEY
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: USER_KEY
        - name: BD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: BD_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Namespace
metadata:
  name: jjaramillo
  ##namespace: jjaramillo
spec:
  selector:
    app: curso-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32254
  type: NodePort
