apiVersion: apps/v1
kind: Deployment
metadata:
  name: curso-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curso-devops
  template:
    metadata:
      labels:
        app: curso-devops
    spec:
      containers:
      - name: app
        image: jnjaramillom/curso-devops-lab3:latest
        ports:
        - containerPort: 3000